import { useState } from 'react';
import { useAtom } from 'jotai';
import { definitionWordAtom, definitionResultAtom } from '@/store';
import { BookOpen, Volume2 } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { motion } from 'framer-motion';

export function DefinitionGenerator() {
  const [word, setWord] = useAtom(definitionWordAtom);
  const [def, setDef] = useAtom(definitionResultAtom);
  const [loading, setLoading] = useState(false);

  const handleDefine = (e: React.FormEvent) => {
    e.preventDefault();
    if (!word.trim()) return;
    setLoading(true);
    
    // Simulate Definition
    setTimeout(() => {
      setDef({
        word: word,
        phonetic: `/${word.toLowerCase().slice(0, 3)}.../`,
        partOfSpeech: 'noun',
        definition: `A simulated definition for "${word}" generated by the StudyFlow system for demonstration purposes.`,
        example: `The student looked up "${word}" in the digital dictionary.`
      });
      setLoading(false);
    }, 800);
  };

  return (
    <div className="flex flex-col gap-4 h-full">
      <form onSubmit={handleDefine} className="relative">
        <Input 
          placeholder="Define a term..." 
          value={word}
          onChange={(e) => setWord(e.target.value)}
          className="pr-10"
        />
        <Button 
          size="icon" 
          variant="ghost" 
          type="submit"
          className="absolute right-0 top-0 h-full w-10 text-muted-foreground hover:text-primary"
        >
          <BookOpen className="w-4 h-4" />
        </Button>
      </form>

      <div className="flex-1">
        {loading ? (
          <div className="flex items-center gap-2 text-muted-foreground text-xs animate-pulse p-2">
            <div className="w-2 h-2 rounded-full bg-primary" /> Looking up...
          </div>
        ) : def ? (
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white/60 dark:bg-black/20 rounded-xl p-4 border border-white/20"
          >
            <div className="flex items-baseline justify-between mb-2">
              <h3 className="text-xl font-serif font-medium">{def.word}</h3>
              <span className="text-sm font-mono text-muted-foreground">{def.phonetic}</span>
            </div>
            <span className="inline-block text-[10px] font-bold uppercase tracking-wider text-primary bg-primary/10 px-2 py-0.5 rounded mb-3">
              {def.partOfSpeech}
            </span>
            <p className="text-sm leading-relaxed text-foreground/90 mb-3">
              {def.definition}
            </p>
            <div className="pl-3 border-l-2 border-primary/20">
              <p className="text-xs text-muted-foreground italic">"{def.example}"</p>
            </div>
          </motion.div>
        ) : (
          <div className="text-center py-10 text-muted-foreground/40">
             <p className="text-xs">Enter a word to get started</p>
          </div>
        )}
      </div>
    </div>
  );
}
